name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"embeds\":[{
              \"title\":\"🚀 New Push di ${{ github.repository }}\",
              \"url\":\"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\",
              \"color\":5763719,
              \"description\":\"${{ github.event.head_commit.message }}\",
              \"fields\":[
                {\"name\":\"👤 Author\",\"value\":\"${{ github.event.head_commit.author.username }}\",\"inline\":true},
                {\"name\":\"🧑‍💻 Committer\",\"value\":\"${{ github.event.head_commit.committer.name }}\",\"inline\":true},
                {\"name\":\"📤 Pushed by\",\"value\":\"${{ github.actor }}\",\"inline\":true},
                {\"name\":\"🌿 Branch\",\"value\":\"${{ github.ref_name }}\",\"inline\":true},
                {\"name\":\"🔢 Commit\",\"value\":\"\`${{ github.sha }}\",\"inline\":false}
              ],
              \"timestamp\":\"${{ github.event.head_commit.timestamp }}\"
            }]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
